services:
  device:
    build: 
      context: device
      dockerfile: Dockerfile
    privileged: true
    networks:
      - default
    restart: always

  web:
    build: 
      context: web
      dockerfile: Dockerfile
    ports:
      - "42586:5000"
    depends_on:
      - device
    networks:
      - default
    restart: always

networks:
  default:
    driver: bridge